version: '3'
services:
  flask:
    build:
      context: ./
    image: flask-user
    environment:
      ENV: prod
    ports:
      - "81:5000"
    entrypoint: python /app/app.py
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped

  testserver:
    build:
      context: ./
      dockerfile: ./test/Dockerfile
    image: pytest-image 
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      ENV: dev 
      # APPLICATION_PORT: 5053
      # APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest . 

  testdb:
    image: mongo:4.0.8 
    container_name: testdb
